name: Publish operator
description: Action to publish operator

inputs:
  operator_name:
    required: true
    description: "The name of the operator."
  operator_version:
    required: true
    description: "The version of the operator."
  operator_bundle_directory:
    required: true
    default: ${{ github.workspace }}
    description: "The directory to change into."
  pr_body_template_url:
    required: true
    description: URL to download the PR body template
  repository_origin_owner:
    description: "The owner of the repository"
    required: true
    type: string
  repository_origin_name:
    description: "The name of the repository"
    required: true
    type: string
  repository_upstream_owner:
    description: "The owner of the repository"
    required: true
    type: string
  repository_upstream_name:
    description: "The name of the repository"
    required: true
    type: string
  repository_default_branch:
    description: "The default branch name of the repository"
    required: true
    type: string
secrets:
  GITHUB_PAT:
    required: true

runs:
  using: "composite"
  steps:
    - name: Origin - checkout ${{ inputs.repository_origin_owner }}/${{ inputs.repository_origin_name }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository_origin_owner }}/${{ inputs.repository_origin_name }}
        path: origin_repository
        token: ${{ secrets.GITHUB_PAT }}
    - name: Origin - Sync with upstream
      working-directory: origin_repository
      run: |
        git remote add upstream https://github.com/${{ inputs.repository_upstream_owner }}/${{ inputs.repository_upstream_name }}.git
        git fetch upstream                     
        git checkout ${{ inputs.repository_default_branch }}
        git reset --hard upstream/${{ inputs.repository_default_branch }}
        git push origin ${{ inputs.repository_default_branch }} -f
    - name: Origin - prepare branch for PR
      run: |
        export branch_name = ${{ inputs.operator_name }}-${{ inputs.operator_version }}

        cd origin_repository
        git fetch origin
        git branch -d ${branch_name} &> /dev/null || true
        git push origin -d ${branch_name} &> /dev/null || true
        git checkout -b ${branch_name}
        cd ..

        mkdir -p origin_repository/operators/${{ inputs.operator_name }}
        cp -R ${{ inputs.operator_bundle_directory }} origin_repository/operators/${{ inputs.operator_name }}/${{ inputs.operator_version }}/

        cd origin_repository
        git add operators/${{ inputs.operator_name }}/${{ inputs.operator_version }}/\*
    - name: Origin - commit & push branch for PR
      uses: project-openubl/.github/actions/commit@master
      with:
        working-directory: origin_repository
        branch: ${{ inputs.operator_name }}-${{ inputs.operator_version }}
        commit_message: "Release operator ${{ inputs.operator_version }}"
    - name: Create PR in upstream
      run: |
        curl -o pr-body.md ${{ inputs.pr_body_template_url }}
        export PR_BODY_FILE=$(readlink -f pr-body.md)

        gh pr create \
        -H ${{ inputs.repository_origin_owner }}:${{ inputs.operator_version }} \
        -R ${{ inputs.repository_upstream_owner }}/${{ inputs.repository_upstream_name }} \
        -B ${{ inputs.repository_default_branch }} \
        -t "operator ${{ inputs.operator_name }} (${{ inputs.operator_version }})" \
        -F $PR_BODY_FILE
      env:
        GH_TOKEN: ${{ secrets.GITHUB_PAT }}
